### ISSUE TITLE
No aparecen algunas las redes sociales de un usuario en la página de un evento

### ISSUE THREAD

**Issue by tamayonauta** [ColombiaPython/sitio-web#101]
Si un usuario solamente tiene Linkedin o Instagram, en la página del evento no aparece ninguna red social de ese usuario.
Con página del evento me refiero a esto: https://www.python.org.co/eventos/2018/11/taller-programacion-mujeres-pereira/

**Comment by goanpeca** [comment]
@aerendon puedes darle una mirada?

**Comment by rlaverde** [comment]
https://github.com/ColombiaPython/sitio-web/blob/develop/templates/django-girls.html#L71
Linkedin e instagram no se estan añadiendo, lo malo es que si alguien tiene muchas no se va a ver bien
