### ISSUE TITLE
No se puede hacer zoom en la página de un evento

### ISSUE THREAD

**Issue by tamayonauta** [ColombiaPython/sitio-web#103]
Al parecer en iOS si funciona, pero no en Android.
OS: Android 5.1 y 7.1
Browser: Google Chrome

**Comment by arendondiosa** [comment]
Especificamente Zoom en qué sección del evento?

**Comment by tamayonauta** [comment]
En cualquier parte. Lo más importante es que se pueda hacer en las imágenes como la del timeline. @aerendon

**Comment by arendondiosa** [comment]
@goanpeca sugiero colocar las imagenes en un modal al hacer click.
¿O sugiere alguna otra solución?

**Comment by goanpeca** [comment]
@aerendon si, es una opción, puede funcionar :-)
