### ISSUE TITLE
Error en la URL del evento

### ISSUE THREAD

**Issue by tamayonauta** [ColombiaPython/sitio-web#104]
La URL que se definió del evento es:
https://develop.python.org.co/eventos/2018/11/taller-mujeres-bogota/

Sin embargo, ahora existe otra URL:
https://develop.python.org.co/eventos/2018/11/taller-programacion-mujeres-bogota/

Las dos URLs funcionan, pero en la primera URL se rompen las imágenes.

**Comment by goanpeca** [comment]
@tamayonauta yo cambié a https://develop.python.org.co/eventos/2018/11/taller-programacion-mujeres-bogota/ que es lo que se está usando en todos los demás eventos.

`bogota.tallerdeprogramacion.co` apunta ya a 

`https://www.python.org.co/eventos/2018/11/taller-programacion-mujeres-bogota/`

**Comment by tamayonauta** [comment]
@goanpeca vale, no sabía eso. Sin embargo, la primera URL debería dar 404.

**Comment by goanpeca** [comment]
>Sin embargo, la primera URL debería dar 404.

Lo hará cuando se limpie el cache de Cloudfare (no estoy seguro cuanto toma eso.. si horas o días)
