### ISSUE TITLE
Ocultar botones de inscripción

### ISSUE THREAD

**Issue by arendondiosa** [ColombiaPython/sitio-web#118]
@goanpeca @EllaQuimica se deberian ocultar los botones de Inscripción cuando se pase la fecha?

**Comment by goanpeca** [comment]
@aerendon en teoría yo diría que si, pero lo que se ha manejado tradicionalmente es que no se esconden para que las personas que igual se quieren registrar después de las fechas establecidas lo puedan hacer, lo que nos permite tener la base de datos de gente intersada (sean guías o asistentes potenciales) para los siguientes eventos.
