### ISSUE TITLE
Información en el footer

### ISSUE THREAD

**Issue by arendondiosa** [ColombiaPython/sitio-web#14]
Detallar información
- Contacto
- Redes sociales
- Privacidad

**Comment by goanpeca** [comment]
@aerendon revisa a ver que más podemos poner por favor 

https://colombiapython.github.io/sitio-web-desarrollo/

**Comment by arendondiosa** [comment]
@goanpeca Pregunta técnica.
Voy a colocar nuestras redes con Icons (https://fontawesome.com/)
Uso un CDN ó adjunto los archivos?

**Comment by goanpeca** [comment]
hmmmm digamos que por garantizar la estabilidad del sitio archivos...
pero CDN tal vez es mas rapido por ahora?

**Comment by arendondiosa** [comment]
Pues la teoría dice que CDN= Rápido + Nunca va a dejar de existir el archivo
Y pues lo de rápido por ahora si lo confirmo

**Comment by goanpeca** [comment]
Dale! lo dejo a tu juicio !
