### ISSUE TITLE
Agregar total de eventos

### ISSUE THREAD

**Issue by arendondiosa** [ColombiaPython/sitio-web#141]
Agregar contador de eventos en inicio y vista de eventos

**Comment by goanpeca** [comment]
De eventos futuros?

O de eventos totales?

**Comment by arendondiosa** [comment]
De los dos podría ser:
_xx/xxxx_ ó _Próximos Eventos: xx, Eventos Pasados: xx_

**Comment by goanpeca** [comment]
hecho
