### ISSUE TITLE
Actualización Link del tutorial en Django Girls Colombia

### ISSUE THREAD

**Issue by EllaQuimica** [ColombiaPython/sitio-web#148]
Hola @arendondiosa 

Podrías ayudarnos con la actualización del link que redirecciona al tutorial, el tutorial que seguiremos usando este 2019 es  https://tutorial.djangogirls.org/es/  y no https://argentinaenpython.com/django-girls/tutorial/

En este caso en los eventos que hemos organizado en el 2019 - PyCon y Pasto

cc @goanpeca

**Comment by goanpeca** [comment]
El link dentro del texto del evento o ?

tallerdeprogramacion.co ?
