### ISSUE TITLE
Incluir nuevo sponsor en DGPasto

### ISSUE THREAD

**Issue by EllaQuimica** [ColombiaPython/sitio-web#149]
Hola @arendondiosa  y @goanpeca , me ayudarían incluyendo este sponsor en el django girls pasto, porfa.

Logo https://kommit.co/static/media/logo-kommit.76d39483.svg

**Comment by goanpeca** [comment]
Fixed by https://github.com/ColombiaPython/sitio-web/commit/950aa4100d208749765f4689261bc13baff2f8e3
