### ISSUE TITLE
Añadir meetup Python Cartagena -  Lista de Eventos

### ISSUE THREAD

**Issue by EllaQuimica** [ColombiaPython/sitio-web#153]
Hola @goanpeca y @arendondiosa sería posible incluir en la sección de eventos el próximo meetup de Python Cartagena

Link : https://www.meetup.com/es-ES/pythonctg/events/260013091/
Fecha el Sábado 30 de Marzo, 2019

**Comment by goanpeca** [comment]
https://www.python.org.co/eventos/2019/03/primer-vistazo-a-docker-y-a-ci-cd/
