### ISSUE TITLE
Incluir PyDay realizados dentro de la sección PyDay

### ISSUE THREAD

**Issue by EllaQuimica** [ColombiaPython/sitio-web#157]
Falta incluir una lista de los eventos realizados de la categoría PyDay 

2018 PyDay Cali -  https://www.calidev.co/eventos/pyday/
2019 PyDay Pereira - https://pereira.pyday.co/
![Screenshot_2019-04-02 PyDay Python Colombia](https://user-images.githubusercontent.com/10503343/55420889-67df2c80-554e-11e9-8c2a-ad585b2c8f58.png)

**Comment by goanpeca** [comment]
<img width="1032" alt="Screen Shot 2019-07-06 at 18 08 09" src="https://user-images.githubusercontent.com/3627835/60761940-45f7b900-a019-11e9-83a8-926da3a246e9.png">
hecho
