### ISSUE TITLE
Sobre nosotros

### ISSUE THREAD

**Issue by goanpeca** [ColombiaPython/sitio-web#18]
Hacer el contenido para la sección de sobre nosotros

http://demo.themefisher.com/themefisher/bingo/onepage-slider.html

<img width="1175" alt="screen shot 2018-02-22 at 21 14 15" src="https://user-images.githubusercontent.com/3627835/36574795-5bf6f35c-1815-11e8-9906-826938721125.png">

**Comment by pyjavo** [comment]
¿Repetimos la información que aparece en el home o esta sección no hace falta para el MVP? @goanpeca @jhonjairoroa87

**Comment by goanpeca** [comment]
Creo que la idea es extenderse, creo que la idea no es repetir lo de la página de inicio

**Comment by arendondiosa** [comment]
Yo creo que en el inicio debería ir solo hasta acá 
![image](https://user-images.githubusercontent.com/14989202/37858858-023e5fd2-2ed9-11e8-9320-226f933144da.png)

La parte de las ciudades debería ir ya en la sección de _Sobre Nosotros_

**Comment by pyjavo** [comment]
Entendido @aerendon 

1. ¿Les parece si las ciudades las incluimos acá? http://develop.python.org.co/sobre-nosotros/
2. Un mapa con pines de las ubicaciones y enlaces
3. Solo el listado de las comunidades con enlaces

**Comment by arendondiosa** [comment]
@javierdaza correcto
Seria bastante interesante tener una especie de mapa interactivo, y que con cada pin de información del respectivo grupo.

Por ejemplo [Leaflet](https://leafletjs.com/) me ha parecido muy apropiado para estas cosas

**Comment by pyjavo** [comment]
¡Que bien!
Si bien el mapa lo hace interactivo, desde el punto de vista de SEO me parece que no es muy amigable. Por ello sugiero en mantener la lista de texto también. Si no es en la página principal ¿en que otro lugar podríamos ubicar la lista? ¿Que opinas?

**Comment by arendondiosa** [comment]
Por ejemplo en https://nodeschool.io manejan los eventos de las dos maneras y en la misma vista

![image](https://user-images.githubusercontent.com/14989202/41416580-d314a5cc-6fb0-11e8-949f-aed9bcc68a44.png)

O podría ser como una opción de visualización: Ordenar en lista ó visualizar el mapa

**Comment by pyjavo** [comment]
Uff, ¡lo de nodeschool esta genial! Esa es la solución parce. Hagámosle, no le demos vueltas al asunto. 
¿Podrías ayudarnos con ese PR @aerendon ?

**Comment by arendondiosa** [comment]
Yo me encargo del mapa :+1:

**Comment by arendondiosa** [comment]
@goanpeca aquí seguiría el mapa o es en otra parte?

**Comment by goanpeca** [comment]
@aerendon hmmm no estoy seguro. La idea es en el _home_  o en una sección que se llame comunidades o algo así?

No sé la verdad :-|

Pero para ir adelantando, puedes ponerla en algún lugar? tu decide donde y una vez puesto podemos mirar si se ve bien o no. Lo importante es obtener los datos de la DB de lektor. Como todas las comunidades ya tienes la ubicación podemos crear un databag que almacene las coordenadas  y usar eso para generar el json que puede ser parte de la plantilla directamente.

Te sugiero que crees la plantilla del mapa como un `macro` de jinja2 en un archivo aparte para poderlo reubicar fácilmente de  ser necesari.

https://www.getlektor.com/docs/api/databags/ (soporta json así que puedes poner ahí directamente le json de las coordenadas)

Y podemos añadirle a los modelos de usuario un `bool` que diga algo como. `Mostrar en Mapa`

Qué opinas?
