### ISSUE TITLE
Webpack o Rollup

### ISSUE THREAD

**Issue by goanpeca** [ColombiaPython/sitio-web#19]
Nice to have: Compilar assets

**Comment by goanpeca** [comment]
Tienes alguna recomendación sobre uno u otro? creo que webpack tiene más sentido para lo que hacemos. Vale la pena incluirlo?

**Comment by Scot3004** [comment]
Depende, de pybaq toco retirarlo porque el ciclo de vida de aplicaciones node tiende a ser mas rápido que el de las aplicaciones python, y que tan activamente se va a a actualizar los assets

**Comment by Scot3004** [comment]
Hola, se que esta un poco congelado este issue, pero justo estoy enfrentando este dilema, alguna segunda opinion?

**Comment by goanpeca** [comment]
Pues yo creo que por ahora podemos cerrar este issue, y hacernos la vida más fácil. 

Creo que vale la pena retomar esto cuando se haga el rediseño de la página
