### ISSUE TITLE
Job travis ya no funciona

### ISSUE THREAD

**Issue by Scot3004** [ColombiaPython/sitio-web#194]
Ahora mismo si intentase hacer un despliegue de esta pagina no se podria ya que el deploy en travis.org se rompio, alternativas, usar github actions o algun otro provider, o intentar mudarse a travis.com, en lo personal prefiero github actions

Update:

Se escribio un workflow que funciona con github actions, sin embargo el mismo no está funcionando debido a que el token `GITHUB_TOKEN` Está limitado al mismo repositorio

Se plantean 2 posibles soluciones:
- Tener la rama gh-pages en este mismo repositorio, eliminando el paso intermedio de la imagen de develop (en contra posición se puede usar [GitHub Codespace](https://github.com/features/codespaces) para realizar las pruebas en cada una de las ramas de PR tal como funciono para este PR https://github.com/ColombiaPython/sitio-web/pull/190
- Generar un token con permiso de escritura a nivel de la cuenta de python colombia y actualizar el workflow para usar este token, tocaria darle permisos de escritura sobre los repositorios https://github.com/ColombiaPython/sitio-web-produccion y https://github.com/ColombiaPython/sitio-web-desarrollo

**Comment by arendondiosa** [comment]
Todo el flujo de pruebas y despliegue fue migrado a GitHub Actions
