### ISSUE TITLE
Hacer que el menú muestre la sección en la que se encuentra el usuario

### ISSUE THREAD

**Issue by goanpeca** [ColombiaPython/sitio-web#44]
<img width="370" alt="screen shot 2018-07-12 at 15 18 13" src="https://user-images.githubusercontent.com/3627835/42657212-36863520-85e7-11e8-9739-f2eabf35a455.png">

Ver:
- https://github.com/pybee/pybee.github.io/blob/lektor/templates/layout.html#L3
- https://github.com/pybee/pybee.github.io/blob/lektor/templates/layout.html#L79

**Comment by pyjavo** [comment]
¿Por cual razón cerraron este issue @aerendon ?

**Comment by arendondiosa** [comment]
@javierdaza  #59
