### ISSUE TITLE
Centrar el contenido de las columnas en los diferentes eventos de Django Girls

### ISSUE THREAD

**Issue by goanpeca** [ColombiaPython/sitio-web#45]
Por ejemplo
ver http://develop.python.org.co/eventos/2018/07/django-girls-barranquilla/

<img width="1079" alt="screen shot 2018-07-12 at 15 22 55" src="https://user-images.githubusercontent.com/3627835/42657313-7d04df74-85e7-11e8-8f30-d8aedb7c57e9.png">

Esta fue una "solución" temporal para poder ajustar el número de elementos https://github.com/ColombiaPython/sitio-web/blob/develop/templates/event-dg.html#L21 , pero la idea es arreglar esto y central el contenido

**Comment by arendondiosa** [comment]
Este issue se solucionó con la clase `row justify-content-md-center` después de agregar Bootstrap 4.x al proyecto
