### ISSUE TITLE
Actualizar la página de comunidades con los miembros

### ISSUE THREAD

**Issue by goanpeca** [ColombiaPython/sitio-web#47]
Mira @aerendon (hasta que un parche de lektor permita varios tipos de modelo como hijos en `users`) todo lo puse en un solo modelo.

No es lo ideal pero es conveniente por ahora. https://github.com/ColombiaPython/sitio-web/blob/develop/models/user.ini#L144

Comove ves, un usuario puede tener miembros y son otros usuarios. La idea es usarlo para que todo lo que NO sea una `persona` pueda ser agregado a otros usuarios como miembro.

De esa forma podemos hacer algo como
https://develop.python.org.co/usuarios/python-bucaramanga/

La idea es mejorar la presentación y utilizar la lógica de las fechas. Es decir podemos poner antiguos miembros "cargos" y si están vigentes o no, lo que permite mostrar un poco de esa historia

Estos modelos que relacionan cosas con otros modelos son `flowblocks` https://www.getlektor.com/docs/content/flow/

y este en particular está descrito acá https://github.com/ColombiaPython/sitio-web/blob/develop/flowblocks/member.ini

@ColombiaPython/sitio-web ideas sobre que más se podría hacer acá?

**Comment by arendondiosa** [comment]
Actualmente cada comunidad tiene los miembros actuales y antiguos, segú nel requerimiento

_Ejemplo:_

![image](https://user-images.githubusercontent.com/14989202/48318387-0da8f380-e5ce-11e8-89cc-6fbf02d4d488.png)
