### ISSUE TITLE
Incluir boton de registro Guías y Participantes

### ISSUE THREAD

**Issue by EllaQuimica** [ColombiaPython/sitio-web#48]
Incluir en los eventos los botones de registro, aúnque haya pasado.

**Comment by goanpeca** [comment]
A qué te refieres @EllaQuimica ?

<img width="436" alt="screen shot 2018-07-13 at 10 32 32" src="https://user-images.githubusercontent.com/3627835/42700016-1978307c-8688-11e8-9598-43d990d99ee6.png">
