### ISSUE TITLE
Logos de organizadores en la sección contacto

### ISSUE THREAD

**Issue by EllaQuimica** [ColombiaPython/sitio-web#49]
Incluir los logos de los organizadores en la sección de contacto del evento.

**Comment by goanpeca** [comment]
Fixed on https://github.com/ColombiaPython/sitio-web/compare/e646b29a7176...af532cd97608

**Comment by goanpeca** [comment]
<img width="1421" alt="screen shot 2018-07-13 at 11 07 48" src="https://user-images.githubusercontent.com/3627835/42701746-023db0d0-868d-11e8-8520-4a90a40a2f2e.png">
