### ISSUE TITLE
Crear pagina del código de conducta

### ISSUE THREAD

**Issue by goanpeca** [ColombiaPython/sitio-web#5]

**Comment by pyjavo** [comment]
Ejemplo https://github.com/PyBAQ/codigo-de-conducta

**Comment by goanpeca** [comment]
Y este https://github.com/colombia-dev/codigo-de-conducta? y simplemente referenciarlo?

Qué le falta al de colombia dev? creo que me gusta más la idea de unificar, es decir hacer un Fork del código de conducta de colombia-dev con una pequeña nota, y estar pendientes cada cierto tiempo de cambios en el de colombia dev (que creo que no ha cambiado hace rato?).

Cualquier aporte lo podemos unificar ahí también si queremos expandirlo

**Comment by arendondiosa** [comment]
A mi me parece que el código de Conduca de _Colombia-dev_ es adecuado para aplicarlo en *Python Colombia*

La verdad no creo que sea necesario crear uno de cero.

**Comment by goanpeca** [comment]
@ColombiaPython/admin esto es muy importante porque todas las inciativas que se desprenden y forman parte de Python Colombia van a utilizar este código de conducta, django girls, pyladies los meetups y la conferencia
