### ISSUE TITLE
Incluir Galería de fotos en el home de Django Girls 

### ISSUE THREAD

**Issue by EllaQuimica** [ColombiaPython/sitio-web#72]
Incluir los 3 últimos eventos con fotito y que esto lleve a la galería de eventos Django Girls

**Comment by goanpeca** [comment]
@EllaQuimica para poder hacer esto sugiero que usemos un servicio (como google photos) para subir todas las fotos por evento y así poner enlaces a esas galerías en vez de incluir directamente las fotos en el sitio. Eso lo hace muy pesado a medida que pasa el tiempo y menos eficiente.

Está bien incluir un par de fotos destacadas (esas si como parte del sitio/repositorio) pero aún así eso también podría ser un album dentro del servicio que se escoja.

Podrías hacer una prueba subiendo un album de fotos de un evento a la cuenta de djangogirlscolombia@gmail.com (ver https://photos.google.com/) tengo entendido que si uno acepta la compresión de fotos de google, el espacio es ilimitado.

**Comment by goanpeca** [comment]
@aerendon qué opinas de subir estas fotos a la cuenta de google de dg colombia?

Tu tienes acceso a ese correo?

**Comment by arendondiosa** [comment]
1. Estaba pensando en hacer una galeria usando [Carousel Bootstrap](https://getbootstrap.com/docs/4.0/components/carousel/), pero nunca he usado fotos desde drive (@goanpeca no sé si tenga alguna idea en mente que me ayude)

2. No tengo acceso a ese drive

**Comment by goanpeca** [comment]
1.) La idea es no tener la fotos dentro del repositorio, porque cada vez es más pesado. Entonces la idea era tener las fotos como galerías de google photos embebidas.

**Comment by arendondiosa** [comment]
Se encuentra una [solución](https://stackoverflow.com/questions/20681974/how-to-embed-a-google-drive-folder-in-a-website)

![image](https://user-images.githubusercontent.com/14989202/44292393-e0a4a900-a249-11e8-902b-81878756871a.png)

- Requiere un enlace a una carpeta pública de Google drive (El anterior es un ejemplo de aplicar la solución)

**Comment by arendondiosa** [comment]
Lo que hice de momento fue añadir un bloque en el modelo `evento-dg`:
![image](https://user-images.githubusercontent.com/14989202/44299342-86dbc780-a2b9-11e8-9b13-a62d25e3f09a.png)

Y ya para la vista preguntar si el campo tiene el string requerido. Si lo tiene procede a renderizar el iframe de drive:

![image](https://user-images.githubusercontent.com/14989202/44299354-b68acf80-a2b9-11e8-8774-152aa91055fa.png)

_En este momento lo renderizo al final de cada evento_

**Comment by goanpeca** [comment]
@aerendon genial, creo que yo había creado un campo para las fotos, no podríamos utilizar ese ?
```
[fields.photos]
label = Sitio web de las fotos (google para embeber?)
type = url
width = 1/2
```


Crees que tal vez sea mejor poner las fotos al principio del evento? con algún texto extra en caso de que hayan fotos?

Por ejemplo si la fecha es mayor al evento, que diga este evento ya finalizó y fu un éxito!, pronto estaremos publicando las fotografías (si no hay fotos), y si hay fotos algo como: A continuación puedes ver las fotos del evento!

Así podemos capturar la atención de entrada a los que visiten las páginas.

Voy a tratar de subir todas las fotos de todos los eventos este fin de semana a ver si podemos dejar esto enlazado. 

Sobre los nombres de las fotos, tal vez mejor esconderlo?

**Comment by arendondiosa** [comment]
Siendo una URL se tendría que parsear para sacar el ID ya que en el iframe no se coloca la URL como la entrega drive.

Para el segundo punto si estoy de acuerdo...acomodar al principio del evento es más atractivo. CC @ellaquimica
