### ISSUE TITLE
Incluir sección de redes y contacto en el home de Django Girls

### ISSUE THREAD

**Issue by EllaQuimica** [ColombiaPython/sitio-web#73]
* email: djangogirlscolombia@gmail.com
* Facebook: https://www.facebook.com/djangogirlscolombia/
* Instagram:  https://www.instagram.com/djangogirlsco/
* Twitter: https://twitter.com/DjangoGirlsCo
* Medium: https://medium.com/@djangogirlscolombia

**Comment by arendondiosa** [comment]
@goanpeca esto lo editamos en el markdown o en una vista diferente a `page.html` creamos una sección con iconos? (O de pronto hay una solución que no implique crear toda una vista diferente)
