### ISSUE TITLE
Incluir core team y equipo django girls

### ISSUE THREAD

**Issue by EllaQuimica** [ColombiaPython/sitio-web#74]
Core Team
--------------
Angelica 
Carolina
Javier Daza
Jhon Jairo Roa
Gonzalo
Johanna Sanchez

Equipo Django Girls
--------------------------
Ana Elles
Melissa
Isabel 
Paula
Sorely
Milton

**Comment by goanpeca** [comment]
@aerendon si quisieramos usar la información de los `usuarios` tendriamos que definir lo de `core` vs `equipo`, una opción es con el texto del cargo que tenemos en el `flowblock` así podemos seguir usando los modelos que ya están definidos en http://develop.python.org.co/usuarios/django-girls-colombia/

**Comment by arendondiosa** [comment]
@goanpeca vamos a ver si entiendo la sugerencia:

1. Obtener el usuario `django-girls-colombia`
2. En el punto 1 ya tendriamos la lista de usuarios relacionados al grupo
3. Con el atributo `Cargo` de cada usuario definiriamos si es `core` o `equipo`

Ese sería el flujo de trabajo?

**Comment by goanpeca** [comment]
correcto

**Comment by arendondiosa** [comment]
@EllaQuimica cambié el titulo de equipo DG por colaboradores, ya que Equipo DG lo asigné a Core team + Colaboradores

Para agregar un miembro al core basta con colocar `core` en el cargo del miembro en la vista del admin, o `equipo` para un colaborador

![image](https://user-images.githubusercontent.com/14989202/44157084-28bfa200-a077-11e8-8c8c-a03517924474.png)

**Comment by goanpeca** [comment]
@aerendon necesitamos dejar este detalle documentado en algún lugar
