### ISSUE TITLE
Incluir sección de blog/post en el home de Django Girls

### ISSUE THREAD

**Issue by EllaQuimica** [ColombiaPython/sitio-web#75]
Incluir una sección que vaya mostrando los post escritos por django girls colombia - ahora esta publicados en Medium

https://medium.com/@djangogirlscolombia

**Comment by goanpeca** [comment]
@EllaQuimica todos esos blogs ya están dentro de la página cómo tal, no veo la necesidad de hacer el enlace a medium?
