### ISSUE TITLE
Crear logo de python colombia sin fondo

### ISSUE THREAD

**Issue by goanpeca** [ColombiaPython/sitio-web#8]

**Comment by pyjavo** [comment]
Veo que ya se agrego la información en la página http://develop.python.org.co/django-girls/
¿Qué mas falta de este issue? @EllaQuimica

**Comment by goanpeca** [comment]
No entiendo @javierdaza. ¿Cuál es la relación entre este reporte y el enlace que compartes?

**Comment by pyjavo** [comment]
@goanpeca ups 🙊había leído `logo de Django Girls Colombia`. My mistake
