### ISSUE TITLE
Cambiar el color de enlaces y orden de eventos en página DG

### ISSUE THREAD

**Issue by goanpeca** [ColombiaPython/sitio-web#83]
1.) @aerendon podemos invertir el orden de los años
Creo que es más cómodo para la navegación tener los eventos más recientes primero (2018 ... 2017). Qué opinas?

2.) Podemos buscar opciones de colores con mejor contraste para correo y medium?

<img width="1024" alt="screen shot 2018-08-17 at 11 56 11" src="https://user-images.githubusercontent.com/3627835/44278813-e16f1800-a214-11e8-9aa4-8e26dcfb8f3a.png">

**Comment by arendondiosa** [comment]
De acuerdo en ambos puntos.
Voy a crear un issue de mejora para que los años de los eventos no queden estáticos en el futuro (De momento "quemé" la funcionalidad para los años 2017 y 2018)

**Comment by arendondiosa** [comment]
> Issue #84 para mejora futura
