### ISSUE TITLE
Añadir contenido sobre PyDay

### ISSUE THREAD

**Issue by goanpeca** [ColombiaPython/sitio-web#89]
Crear una página `PyDay` donde se explique que son, cómo funcionan, cuál es la idea de ese tipo de eventos y de paso se pueden mostrar los PyDays que se hayan realizado en Colombia. Por ahora solo saldría el de Cali.

Ver:
- https://www.python.org.co/django-girls/ 
- https://www.python.org.co/pyladies/ 
- https://www.python.org.co/pycon/

**Comment by sebastian-code** [comment]
Sugiero lo siguiente para empezar:

El PyDay es una jornada libre y gratuita de charlas, donde se ve el compromiso de la comunidad y sus organizadores para crear un espacio amable, entretenido y seguro, en el que profesionales, aficionados y curiosos de todos los trasfondos puedan encontrarse, conocerse y aprender un poco mas sobre Python, y todas esas tecnologías y buenas practicas con las que se puede sacar el máximo provecho de nuestro lenguaje de desarrollo favorito, y que nace de ver el gran interés de las comunidades locales para las que los MeetUp a veces se quedan cortos, y el siempre presente _"deseo de mas"_ que tiene el espíritu de sus miembros.

Con una oferta amplia de temas de gran interés para los profesionales del desarrollo de software y centrada en el lenguaje Python, el objetivo principal del PyDay no es eclipsar eventos de mayor envergadura, como los que se hacen bajo el formato de PyCon, si no llenar un vacío presente a nivel local donde se ofrezca gran nivel de conocimiento, actividades que fortalezcan la red de profesionales para encontrar referencias técnicas, una posible mentoría, quizás ese nuevo trabajo que siempre has buscado... y obvio, comida gratis.

**Comment by goanpeca** [comment]
Hola @sebastian-code, muchas gracias por el aporte :-)
