### ISSUE TITLE
Fotos de home y acerca de nosotros

### ISSUE THREAD

**Issue by goanpeca** [ColombiaPython/sitio-web#9]
Buscar unas fotos bien sabrosonas
- Home
- Contacto
- About Us
- Blog

**Comment by pyjavo** [comment]
Fotos reales por favor (de las tomadas en la PyCon). La idea es no verse como una pagina gringa

**Comment by estebanx64** [comment]
Que tal si ponemos como foto del home la de pycon de este año, donde salimos todos en el escenario del auditorio.
