### ISSUE TITLE
Error en la URL de Linkedin

### ISSUE THREAD

**Issue by tamayonauta** [ColombiaPython/sitio-web#99]
Todas las URLs de Linkedin de los usuarios contiene dos https.
Por ejemplo: `https://https//www.linkedin.com/in/username`

**Comment by goanpeca** [comment]
la URL no es lo que hay que poner, es el usuario creo

**Comment by goanpeca** [comment]
Mira el ejemplo https://github.com/ColombiaPython/sitio-web/blob/develop/content/usuarios/goanpeca/contents.lr

**Comment by tamayonauta** [comment]
> Mira el ejemplo https://github.com/ColombiaPython/sitio-web/blob/develop/content/usuarios/goanpeca/contents.lr

Sí, es el usuario. Por favor @goanpeca ver la URL de su Linkedin: https://www.python.org.co/usuarios/goanpeca/

**Comment by goanpeca** [comment]
Tienes, razón, ya lo arreglo :-)

**Comment by goanpeca** [comment]
Fixed on https://github.com/ColombiaPython/sitio-web/commit/5692bbf7176f6695aa0693b6008d5bd92efb238f
